# Generated by Django 5.1.5 on 2025-03-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('contextEra', models.TextField()),
                ('imageEra', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('context', models.TextField(default=0)),
                ('imageWar', models.URLField(default=0)),
                ('belligerents', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('war', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('casualties', models.IntegerField(default=0)),
                ('image', models.URLField(max_length=100)),
                ('imageWar', models.URLField(max_length=100)),
                ('tactics_link', models.CharField(max_length=100)),
                ('tactics', models.TextField()),
                ('imageTactics', models.URLField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('era', models.ManyToManyField(related_name='articles', to='content.era')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.war')),
            ],
        ),
    ]
