# Generated by Django 5.1.6 on 2025-03-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('war', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=100)),
                ('imageWar', models.URLField(max_length=100)),
                ('tactics_link', models.CharField(max_length=100)),
                ('tactics', models.TextField()),
                ('imageTactics', models.URLField(max_length=100)),
                ('context', models.TextField()),
            ],
        ),
    ]
