# Generated by Django 5.1.6 on 2025-04-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='war',
            old_name='context',
            new_name='contextWar',
        ),
    ]
