# Generated by Django 5.1.5 on 2025-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='casualties',
            field=models.IntegerField(default=0),
        ),
    ]
