# Generated by Django 5.1.6 on 2025-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_context_war_contextwar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='contextWar',
            field=models.TextField(default=''),
        ),
    ]
