# Generated by Django 5.1.5 on 2025-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_casualties'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
