# Generated by Django 5.1.6 on 2025-04-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_war_contextwar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='era',
            new_name='eras',
        ),
    ]
