# Generated by Django 5.1.6 on 2025-04-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_era_article_eras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tactics',
        ),
    ]
