# Generated by Django 5.1.6 on 2025-05-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_delete_tactics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='tactics_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
