# Generated by Django 5.1.6 on 2025-05-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_article_description_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageTactics',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='imageWar',
            field=models.URLField(max_length=300),
        ),
    ]
