# Generated by Django 5.1.6 on 2025-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_article_imagetactics_alter_article_imagewar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
